### ISSUE TITLE
SSL Certificate Errors when trying to contact algolia

### ISSUE THREAD

**Issue by benjamine** [algolia/mongo-connector#7] opened 2015-06-09 15:10 UTC
When starting the connector now I'm getting a lot of:

```
CertificateError("hostname \'RA8BA33XSG-3.algolianet.com\' doesn\'t match either of \'*.algolia.io\', \'*.algolia.net\'",
```

perhaps the certificate needs to be updated?

**Comment by redox** [comment] 2015-06-09 15:17
Our servers are using [SNI](http://en.wikipedia.org/wiki/Server_Name_Indication) to support multiple hostnames and all those 3 domain names are supported :/ That's weird... Any idea @asurak & @Nagriar ?

**Comment by asurak** [comment] 2015-06-09 15:31
algolia.net has to work no matter SNI...only when you use IP, it should break

**Comment by redox** [comment] 2015-06-09 15:33
@asurak here the issue is with algoliaNET.com

**Comment by asurak** [comment] 2015-06-09 15:39
Java 6

**Comment by redox** [comment] 2015-06-09 15:45
@benjamine are you using Python 2 or Python 3? Also, could you confirm the version of urllib3 that is used?

**Comment by benjamine** [comment] 2015-06-09 15:45
```
> python --version
Python 2.7.6
```

**Comment by benjamine** [comment] 2015-06-09 15:46
```
>>> import urllib3
>>> urllib3
<module 'urllib3' from '/Library/Python/2.7/site-packages/urllib3-1.10.4-py2.7.egg/urllib3/__init__.pyc'>
```

**Comment by benjamine** [comment] 2015-06-09 15:49
sorry, maybe this piece of stdout is more helpful?:

```
INFO:urllib3.connectionpool:Starting new HTTPS connection (4): RA8BA33XSG.algolia.net
/Library/Python/2.7/site-packages/urllib3-1.10.4-py2.7.egg/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
INFO:urllib3.connectionpool:Starting new HTTPS connection (7): RA8BA33XSG-1.algolianet.com
DEBUG:urllib3.util.retry:Incremented Retry for (url='/1/indexes/products/batch'): Retry(total=2, connect=None, read=None, redirect=None)
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x10baa73d0>, 'Connection to RA8BA33XSG-1.algolianet.com timed out. (connect timeout=1.0)')': /1/indexes/products/batch
INFO:urllib3.connectionpool:Starting new HTTPS connection (8): RA8BA33XSG-1.algolianet.com
/Library/Python/2.7/site-packages/urllib3-1.10.4-py2.7.egg/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
```

**Comment by redox** [comment] 2015-06-09 15:50
It is, debugging-time :+1:, python is killing me....

**Comment by benjamine** [comment] 2015-06-09 15:50
```
InsecurePlatformWarning
New in version 1.11.

Certain Python platforms (specifically, versions of Python earlier than 2.7.9) have restrictions in their ssl module that limit the configuration that urllib3 can apply. In particular, this can cause HTTPS requests that would succeed on more featureful platforms to fail, and can cause certain security features to be unavailable.

If you encounter this warning, it is strongly recommended you upgrade to a newer Python version, or that you use pyOpenSSL as described in the OpenSSL / PyOpenSSL section.
```

I can try upgrading it

**Comment by dethi** [comment] 2015-06-09 15:54
It seems that it doesn't come from your Python version. Get the same error with Python 2.7.9

**Comment by asurak** [comment] 2015-06-09 15:56
What about the version of urllib?

**Comment by redox** [comment] 2015-06-09 15:57
@dethi I just found some interesting stuff here https://urllib3.readthedocs.org/en/latest/contrib.html :)

**Comment by benjamine** [comment] 2015-06-09 16:05
@asurak the version or urllib is on the stdout I pasted `urllib3-1.10.4-py2.7.egg`

**Comment by benjamine** [comment] 2015-06-09 16:06
Now, that was on my local machine OSX, but interestingly, when deploying to my heroku instance (using python 2.7.9), and now sync seem to be working fine there.

**Comment by asurak** [comment] 2015-06-09 16:09
Sorry, missed that output.

I got it. Openssl of OSX is pretty bad, unless you use homebrew version

**Comment by dethi** [comment] 2015-06-10 08:31
Agree with @asurak, try to install OpenSSL from homebrew: brew install openssl

**Comment by Nagriar** [comment] 2015-06-10 09:38
Hi,

I tried the connector with a fresh install (mongo v3.0.3, python 2.7.6, algoliasearch 1.5.4 and urllib3) and I don't have issues to contact algolia even when I force to target a algolianet.com host.

However, I have a warning from urllib3 that can explain the issue: https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.

@benjamine could you try to update your python to see if it's the issue?

**Comment by benjamine** [comment] 2015-06-11 13:11
this problem was solved to me when I tried it on linux with python 2.7.9 (using a heroku dyno), unless someone else is interested, feel free to close this issue.

**Comment by redox** [comment] 2015-06-11 19:34
OK, let's close it then; not very nice :/

**Closed as completed by redox** 2015-06-11 19:34 UTC
